services:
    init-app:
        build: .
        restart: on-failure
        ports:
            - 3000:3000
        depends_on:
            mysql_self:
                condition: service_healthy
        networks:
            - backend
        environment:
            DB_TYPE: ${DB_TYPE}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
            PORT: ${PORT}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
        command: sh -c "npm run migration:up"
    sst-making:
        build: .
        restart: on-failure
        ports:
            - 3000:3000
        depends_on:
            mysql_self:
                condition: service_healthy
        networks:
            - backend
        environment:
            DB_TYPE: ${DB_TYPE}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
            PORT: ${PORT}
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
        command: sh -c "npm start && npm run migration:up"
    mysql_self:
        image: mysql:5.7
        restart: on-failure
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - backend
        volumes:
            - /var/lib/mysql-self
        healthcheck:
            test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    backend:
        driver: bridge
